// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WEB_BASED_PATIENT_MANAGEMENT_SYSTEM.Data;

#nullable disable

namespace WEB_BASED_PATIENT_MANAGEMENT_SYSTEM.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260730153018_AddNewbornRecord")]
    partial class AddNewbornRecord
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WEB_BASED_PATIENT_MANAGEMENT_SYSTEM.Models.NewbornMedication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("MedicineGiven")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NewbornRecordId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NewbornRecordId");

                    b.ToTable("NewbornMedications");
                });

            modelBuilder.Entity("WEB_BASED_PATIENT_MANAGEMENT_SYSTEM.Models.NewbornRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApgarScore")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BabyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BedNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CaseNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConsentClientName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConsentGivenBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConsentMidwifeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateTimeDelivered")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateTimeOfAdmission")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateTimeOfDischarge")
                        .HasColumnType("datetime2");

                    b.Property<string>("Diagnosis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MeasurementAbdomen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MeasurementChest")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MeasurementHead")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MeasurementLength")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotherAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotherName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("PlacentaOut")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Weight")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("NewbornRecords");
                });

            modelBuilder.Entity("WEB_BASED_PATIENT_MANAGEMENT_SYSTEM.Models.NewbornVital", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("HeartRate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NewbornRecordId")
                        .HasColumnType("int");

                    b.Property<string>("RespiratoryRate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Temperature")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NewbornRecordId");

                    b.ToTable("NewbornVitals");
                });

            modelBuilder.Entity("WEB_BASED_PATIENT_MANAGEMENT_SYSTEM.Models.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AOG")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("ContactNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("DateOfBirth")
                        .IsRequired()
                        .HasColumnType("date");

                    b.Property<DateTime?>("EDC")
                        .IsRequired()
                        .HasColumnType("date");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Gravida")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("LMP")
                        .IsRequired()
                        .HasColumnType("date");

                    b.Property<string>("MaritalStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Menarche")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Occupation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Religion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TFAL")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("WEB_BASED_PATIENT_MANAGEMENT_SYSTEM.Models.PrenatalRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AOG")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BloodPressure")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("FetalHeartTone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("FundalHeight")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("PatientId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RecordDate")
                        .IsRequired()
                        .HasColumnType("date");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SelectedServices")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Temperature")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Weight")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("PrenatalRecords");
                });

            modelBuilder.Entity("WEB_BASED_PATIENT_MANAGEMENT_SYSTEM.Models.NewbornMedication", b =>
                {
                    b.HasOne("WEB_BASED_PATIENT_MANAGEMENT_SYSTEM.Models.NewbornRecord", "NewbornRecord")
                        .WithMany("Medications")
                        .HasForeignKey("NewbornRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NewbornRecord");
                });

            modelBuilder.Entity("WEB_BASED_PATIENT_MANAGEMENT_SYSTEM.Models.NewbornRecord", b =>
                {
                    b.HasOne("WEB_BASED_PATIENT_MANAGEMENT_SYSTEM.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("WEB_BASED_PATIENT_MANAGEMENT_SYSTEM.Models.NewbornVital", b =>
                {
                    b.HasOne("WEB_BASED_PATIENT_MANAGEMENT_SYSTEM.Models.NewbornRecord", "NewbornRecord")
                        .WithMany("Vitals")
                        .HasForeignKey("NewbornRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NewbornRecord");
                });

            modelBuilder.Entity("WEB_BASED_PATIENT_MANAGEMENT_SYSTEM.Models.PrenatalRecord", b =>
                {
                    b.HasOne("WEB_BASED_PATIENT_MANAGEMENT_SYSTEM.Models.Patient", "Patient")
                        .WithMany("PrenatalRecords")
                        .HasForeignKey("PatientId");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("WEB_BASED_PATIENT_MANAGEMENT_SYSTEM.Models.NewbornRecord", b =>
                {
                    b.Navigation("Medications");

                    b.Navigation("Vitals");
                });

            modelBuilder.Entity("WEB_BASED_PATIENT_MANAGEMENT_SYSTEM.Models.Patient", b =>
                {
                    b.Navigation("PrenatalRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
