// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WEB_BASED_PATIENT_MANAGEMENT_SYSTEM.Data;

#nullable disable

namespace WEB_BASED_PATIENT_MANAGEMENT_SYSTEM.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260831110925_NormalizePatientAndAddService")]
    partial class NormalizePatientAndAddService
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WEB_BASED_PATIENT_MANAGEMENT_SYSTEM.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("date");

                    b.Property<TimeSpan>("AppointmentTime")
                        .HasColumnType("time");

                    b.Property<string>("ContactNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("InProcess")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("PatientName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ServiceType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("WEB_BASED_PATIENT_MANAGEMENT_SYSTEM.Models.Consultation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int?>("RecordId")
                        .HasColumnType("int");

                    b.Property<string>("RecordType")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("ServiceType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("VisitType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId")
                        .IsUnique()
                        .HasFilter("[AppointmentId] IS NOT NULL");

                    b.HasIndex("PatientId");

                    b.ToTable("Consultations");
                });

            modelBuilder.Entity("WEB_BASED_PATIENT_MANAGEMENT_SYSTEM.Models.FamilyPlanningRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Ack_ClientDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ack_ClientPrintedName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ack_ConsentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ack_MethodAccepted")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Ack_ParentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ack_ParentPrintedName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddressBarangay")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddressMunicipality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddressNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddressProvince")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddressStreet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AverageMonthlyIncome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CivilStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientAge")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ClientDateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("ClientEducation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientGivenName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientIdStr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientLastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientMI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientOccupation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MH_AbnormalVaginalDischarge")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MH_BreastCancerMass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MH_Cough14Days")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MH_DisabilitySpecify")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MH_HematomaBruising")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MH_Jaundice")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MH_PhenobarbitalRifampicin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MH_SevereChestPain")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MH_SevereHeadaches")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MH_Smoker")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MH_StrokeHeartHypertension")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MH_UnexplainedVaginalBleeding")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MH_WithDisability")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MethodCurrentlyUsed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MethodCurrentlyUsed_Others")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoOfLivingChildren")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OH_Abortion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("OH_DateOfLastDelivery")
                        .HasColumnType("datetime2");

                    b.Property<string>("OH_Dysmenorrhea")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OH_EctopicPregnancy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OH_FullTerm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OH_Gravida")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OH_HydatidiformMole")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("OH_LastMenstrualPeriod")
                        .HasColumnType("datetime2");

                    b.Property<string>("OH_LivingChildren")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OH_MenstrualFlow")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OH_Para")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OH_Premature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("OH_PreviousMenstrualPeriod")
                        .HasColumnType("datetime2");

                    b.Property<string>("OH_TypeOfLastDelivery")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PE_Abdomen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PE_BloodPressure_Diastolic")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PE_BloodPressure_Systolic")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PE_Breast")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PE_Conjunctiva")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PE_Extremities")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PE_Height")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PE_Neck")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PE_PulseRate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PE_Skin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PE_Weight")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("Pelvic_AbnormalDischarge")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pelvic_AdnexalMassTenderness")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pelvic_CervicalAbnormalities")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pelvic_CervicalConsistency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pelvic_CervicalTenderness")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pelvic_Mass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pelvic_Normal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pelvic_UterineDepth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pelvic_UterinePosition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlanMoreChildren")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReasonChanging")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReasonForFP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReasonForFP_Others")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RecordDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Religion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("STI_AbnormalDischarge")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("STI_AbnormalDischarge_Loc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("STI_HIV_PID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("STI_HistoryTreatment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("STI_PainBurning")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("STI_SoresUlcers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SelectedService")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpouseAge")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SpouseDateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("SpouseGivenName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpouseLastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpouseMI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpouseOccupation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeOfClient")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VAW_HistoryDomesticViolence")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VAW_PartnerDisapprove")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VAW_ReferredTo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VAW_ReferredTo_Others")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VAW_UnpleasantRelationship")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("FamilyPlanningRecords");
                });

            modelBuilder.Entity("WEB_BASED_PATIENT_MANAGEMENT_SYSTEM.Models.NewbornRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApgarScore")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BabyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BedNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CaseNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConsentCivilStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConsentClientAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ConsentClientAge")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ConsentClientDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ConsentClientName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ConsentMidwifeDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ConsentMidwifeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConsentRelationship")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateTimeDelivered")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateTimeOfAdmission")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateTimeOfDischarge")
                        .HasColumnType("datetime2");

                    b.Property<string>("Diagnosis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MeasurementAbdomen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MeasurementChest")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MeasurementHead")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MeasurementLength")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MedicationsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotherAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotherName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("PlacentaOut")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VitalsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Weight")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("NewbornRecords");
                });

            modelBuilder.Entity("WEB_BASED_PATIENT_MANAGEMENT_SYSTEM.Models.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AOG")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("ContactNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("DateOfBirth")
                        .IsRequired()
                        .HasColumnType("date");

                    b.Property<DateTime?>("EDC")
                        .IsRequired()
                        .HasColumnType("date");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Gravida")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("LMP")
                        .IsRequired()
                        .HasColumnType("date");

                    b.Property<string>("MaritalStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Menarche")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Occupation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Religion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TFAL")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Patient");
                });

            modelBuilder.Entity("WEB_BASED_PATIENT_MANAGEMENT_SYSTEM.Models.PrenatalRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("A")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AOG")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("AntenatalDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AssessOtherProblems")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("B2_QuickCheck_Checkboxes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("B2_QuickCheck_Classify")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("B3_RAM_Checkboxes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("B3_RAM_Classify")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BloodPressure")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("BloodType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C2_BabyBefore")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C2_BabyMoving")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C2_Concerns")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C2_Convulsions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("C2_EDC")
                        .HasColumnType("datetime2");

                    b.Property<string>("C2_FHB")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C2_HeavyBleeding")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("C2_LMP")
                        .HasColumnType("datetime2");

                    b.Property<string>("C2_MonthsPregnant")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C2_PlanDeliver")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C2_PregnancyWeek")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C2_Presentation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C2_PreviousComplications")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C2_PriorCaesarian")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C2_PriorPregnancies")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C2_PriorTear")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C2_SmokeDrinkDrugs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C2_Stillbirth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C2_TT4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C2_VaginalBleeding")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C3_PreEclampsia_BP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C3_PreEclampsia_Classify")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C4_Anemia_Classify")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C4_Anemia_ConjunctivalPallor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C4_Anemia_Hemoglobin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("DevelopBirthPlan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EDC")
                        .HasColumnType("datetime2");

                    b.Property<string>("FamilyNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FetalHeartTone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("FundalHeight")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("G")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gravida")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HusbandName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("L")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LMP")
                        .HasColumnType("datetime2");

                    b.Property<string>("MaritalStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Menarche")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Occupation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PatientAddress")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("PatientName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PatientProblems_Checkboxes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PatientProblems_Classify")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PatientProblems_YesNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrenatalVisitsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrioritySigns_Checkboxes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrioritySigns_Classify")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrioritySigns_YesNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RecordDate")
                        .IsRequired()
                        .HasColumnType("date");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SelectedServices")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("T")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TFAL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Temperature")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ThirdTrimester_Checkboxes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThirdTrimester_Classify")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VisitType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Weight")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("PrenatalRecords");
                });

            modelBuilder.Entity("WEB_BASED_PATIENT_MANAGEMENT_SYSTEM.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("Service");
                });

            modelBuilder.Entity("WEB_BASED_PATIENT_MANAGEMENT_SYSTEM.Models.Appointment", b =>
                {
                    b.HasOne("WEB_BASED_PATIENT_MANAGEMENT_SYSTEM.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("WEB_BASED_PATIENT_MANAGEMENT_SYSTEM.Models.Consultation", b =>
                {
                    b.HasOne("WEB_BASED_PATIENT_MANAGEMENT_SYSTEM.Models.Appointment", "Appointment")
                        .WithMany()
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WEB_BASED_PATIENT_MANAGEMENT_SYSTEM.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .IsRequired();

                    b.Navigation("Appointment");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("WEB_BASED_PATIENT_MANAGEMENT_SYSTEM.Models.FamilyPlanningRecord", b =>
                {
                    b.HasOne("WEB_BASED_PATIENT_MANAGEMENT_SYSTEM.Models.Patient", "Patient")
                        .WithMany("FamilyPlanningRecords")
                        .HasForeignKey("PatientId");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("WEB_BASED_PATIENT_MANAGEMENT_SYSTEM.Models.NewbornRecord", b =>
                {
                    b.HasOne("WEB_BASED_PATIENT_MANAGEMENT_SYSTEM.Models.Patient", "Patient")
                        .WithMany("NewbornRecords")
                        .HasForeignKey("PatientId");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("WEB_BASED_PATIENT_MANAGEMENT_SYSTEM.Models.PrenatalRecord", b =>
                {
                    b.HasOne("WEB_BASED_PATIENT_MANAGEMENT_SYSTEM.Models.Patient", "Patient")
                        .WithMany("PrenatalRecords")
                        .HasForeignKey("PatientId");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("WEB_BASED_PATIENT_MANAGEMENT_SYSTEM.Models.Service", b =>
                {
                    b.HasOne("WEB_BASED_PATIENT_MANAGEMENT_SYSTEM.Models.Patient", "Patient")
                        .WithMany("Services")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("WEB_BASED_PATIENT_MANAGEMENT_SYSTEM.Models.Patient", b =>
                {
                    b.Navigation("FamilyPlanningRecords");

                    b.Navigation("NewbornRecords");

                    b.Navigation("PrenatalRecords");

                    b.Navigation("Services");
                });
#pragma warning restore 612, 618
        }
    }
}
