// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WEB_BASED_PATIENT_MANAGEMENT_SYSTEM.Data;

#nullable disable

namespace WEB_BASED_PATIENT_MANAGEMENT_SYSTEM.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20261008152845_GroupClinicalRecordFieldsByCategory")]
    partial class GroupClinicalRecordFieldsByCategory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WEB_BASED_PATIENT_MANAGEMENT_SYSTEM.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("date");

                    b.Property<TimeSpan>("AppointmentTime")
                        .HasColumnType("time");

                    b.Property<string>("ContactNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("InProcess")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("PatientName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ServiceType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("WEB_BASED_PATIENT_MANAGEMENT_SYSTEM.Models.Consultation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int?>("RecordId")
                        .HasColumnType("int");

                    b.Property<string>("RecordType")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("ServiceId")
                        .HasColumnType("int");

                    b.Property<string>("ServiceType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("VisitType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId")
                        .IsUnique()
                        .HasFilter("[AppointmentId] IS NOT NULL");

                    b.HasIndex("PatientId");

                    b.HasIndex("ServiceId");

                    b.ToTable("Consultations");
                });

            modelBuilder.Entity("WEB_BASED_PATIENT_MANAGEMENT_SYSTEM.Models.FamilyPlanningRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AcknowledgementJson")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Category: Acknowledgement / Consent (JSON). Fields: Ack_ClientPrintedName, Ack_ClientDate, Ack_ConsentName, Ack_ParentPrintedName, Ack_ParentDate");

                    b.Property<string>("ClientInfoJson")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Category: Client Information (JSON). Fields: ClientMI, ClientEducation, AddressNo, AddressBarangay, AddressMunicipality, AddressProvince, SpouseLastName, SpouseGivenName, SpouseMI, SpouseDateOfBirth, SpouseAge, SpouseOccupation, NoOfLivingChildren, PlanMoreChildren, AverageMonthlyIncome");

                    b.Property<string>("FamilyPlanningMethodJson")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Category: Family Planning Method / History (JSON). Fields: TypeOfClient, ReasonForFP, ReasonForFP_Others, ReasonChanging, MethodCurrentlyUsed, MethodCurrentlyUsed_Others");

                    b.Property<string>("MedicalHistoryJson")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Category: I. Medical History (JSON). Fields: MH_SevereHeadaches, MH_StrokeHeartHypertension, MH_HematomaBruising, MH_BreastCancerMass, MH_SevereChestPain, MH_Cough14Days, MH_Jaundice, MH_UnexplainedVaginalBleeding, MH_AbnormalVaginalDischarge, MH_PhenobarbitalRifampicin, MH_Smoker, MH_WithDisability, MH_DisabilitySpecify");

                    b.Property<string>("ObstetricalHistoryJson")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Category: II. Obstetrical History (JSON). Fields: OH_Gravida, OH_Para, OH_FullTerm, OH_Premature, OH_Abortion, OH_LivingChildren, OH_DateOfLastDelivery, OH_TypeOfLastDelivery, OH_LastMenstrualPeriod, OH_PreviousMenstrualPeriod, OH_MenstrualFlow, OH_Dysmenorrhea, OH_HydatidiformMole, OH_EctopicPregnancy");

                    b.Property<int?>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("PhysicalExamJson")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Category: V. Physical Examination (JSON). Fields: PE_Height, PE_Weight, PE_BloodPressure_Systolic, PE_BloodPressure_Diastolic, PE_PulseRate, PE_Skin, PE_Conjunctiva, PE_Neck, PE_Breast, PE_Abdomen, PE_Extremities, Pelvic_Normal, Pelvic_Mass, Pelvic_AbnormalDischarge, Pelvic_CervicalAbnormalities, Pelvic_CervicalConsistency, Pelvic_CervicalTenderness, Pelvic_AdnexalMassTenderness, Pelvic_UterinePosition, Pelvic_UterineDepth");

                    b.Property<DateTime?>("RecordDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RiskAssessmentJson")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Category: III-IV. Risks for STI and VAW (JSON). Fields: STI_AbnormalDischarge, STI_AbnormalDischarge_Loc, STI_SoresUlcers, STI_PainBurning, STI_HistoryTreatment, STI_HIV_PID, VAW_UnpleasantRelationship, VAW_PartnerDisapprove, VAW_HistoryDomesticViolence, VAW_ReferredTo, VAW_ReferredTo_Others");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("FamilyPlanningRecords");
                });

            modelBuilder.Entity("WEB_BASED_PATIENT_MANAGEMENT_SYSTEM.Models.NewbornRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApgarScore")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BabyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BedNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CaseNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConsentCivilStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConsentClientAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ConsentClientAge")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ConsentClientDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ConsentClientName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ConsentMidwifeDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ConsentMidwifeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConsentRelationship")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateTimeDelivered")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateTimeOfAdmission")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateTimeOfDischarge")
                        .HasColumnType("datetime2");

                    b.Property<string>("Diagnosis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MeasurementAbdomen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MeasurementChest")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MeasurementHead")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MeasurementLength")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MedicationsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("PlacentaOut")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VitalsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Weight")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("NewbornRecords");
                });

            modelBuilder.Entity("WEB_BASED_PATIENT_MANAGEMENT_SYSTEM.Models.NotificationRead", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReadAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserAccountId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId");

                    b.HasIndex("UserAccountId", "AppointmentId")
                        .IsUnique();

                    b.ToTable("NotificationReads");
                });

            modelBuilder.Entity("WEB_BASED_PATIENT_MANAGEMENT_SYSTEM.Models.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AOG")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("ContactNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("DateOfBirth")
                        .IsRequired()
                        .HasColumnType("date");

                    b.Property<DateTime?>("DateRegistered")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EDC")
                        .IsRequired()
                        .HasColumnType("date");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Gravida")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("LMP")
                        .IsRequired()
                        .HasColumnType("date");

                    b.Property<string>("MaritalStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Menarche")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Occupation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Religion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TFAL")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Patient");
                });

            modelBuilder.Entity("WEB_BASED_PATIENT_MANAGEMENT_SYSTEM.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Amount")
                        .IsRequired()
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("ConsultationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("ConsultationId")
                        .IsUnique();

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("WEB_BASED_PATIENT_MANAGEMENT_SYSTEM.Models.PrenatalRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BirthPlanJson")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Category: Delivery / Follow-up (JSON). Fields: C2_PlanDeliver, DevelopBirthPlan");

                    b.Property<string>("GeneralInfoJson")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Category: General Prenatal Information (JSON). Fields: FamilyNo, AntenatalDate, VisitType, HusbandName");

                    b.Property<string>("LaboratoryJson")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Category: Laboratory / Diagnostic Information (JSON). Fields: BloodType, C4_Anemia_Hemoglobin");

                    b.Property<string>("MaternalHistoryJson")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Category: Maternal History (JSON). Fields: C2_BabyBefore, C2_PriorPregnancies, C2_PriorCaesarian, C2_PriorTear, C2_HeavyBleeding, C2_Convulsions, C2_Stillbirth, C2_PreviousComplications, C2_SmokeDrinkDrugs, C2_TT4");

                    b.Property<string>("ObstetricInfoJson")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Category: Pregnancy / Obstetric Information (JSON). Fields: AOG, T, P, A, L, C2_MonthsPregnant, C2_PregnancyWeek, C2_VaginalBleeding, C2_BabyMoving, C2_FHB, C2_Presentation");

                    b.Property<int?>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("PrenatalVisitsJson")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Prenatal visit rows (JSON list). Fields per visit: RecordDate, AOG, Weight, BloodPressure, Temperature, FundalHeight, FetalHeartTone, Remarks");

                    b.Property<DateTime?>("RecordDate")
                        .IsRequired()
                        .HasColumnType("date");

                    b.Property<string>("RiskAssessmentJson")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Category: Pregnancy Risk / Assessment (JSON). Fields: B2_QuickCheck_Checkboxes, B2_QuickCheck_Classify, B3_RAM_Checkboxes, B3_RAM_Classify, PrioritySigns_YesNo, PrioritySigns_Checkboxes, PrioritySigns_Classify, ThirdTrimester_Checkboxes, ThirdTrimester_Classify, C3_PreEclampsia_BP, C3_PreEclampsia_Classify, C4_Anemia_ConjunctivalPallor, C4_Anemia_Classify, PatientProblems_YesNo, PatientProblems_Checkboxes, PatientProblems_Classify, AssessOtherProblems, C2_Concerns");

                    b.Property<string>("VitalSignsJson")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Category: Vital Signs / Physical Examination (JSON). Fields: Weight, BloodPressure, Temperature");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("PrenatalRecords");
                });

            modelBuilder.Entity("WEB_BASED_PATIENT_MANAGEMENT_SYSTEM.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId");

                    b.HasIndex("PatientId");

                    b.ToTable("Service");
                });

            modelBuilder.Entity("WEB_BASED_PATIENT_MANAGEMENT_SYSTEM.Models.UserAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("LastActivityAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastLoginAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastLogoutAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("PasswordResetCodeExpiresUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordResetCodeHash")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("PasswordResetFailedAttempts")
                        .HasColumnType("int");

                    b.Property<string>("RecoveryEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("UserAccounts", t =>
                        {
                            t.HasCheckConstraint("CK_UserAccounts_ValidRole", "[Role] IN (N'Admin', N'Staff')");
                        });
                });

            modelBuilder.Entity("WEB_BASED_PATIENT_MANAGEMENT_SYSTEM.Models.Appointment", b =>
                {
                    b.HasOne("WEB_BASED_PATIENT_MANAGEMENT_SYSTEM.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("WEB_BASED_PATIENT_MANAGEMENT_SYSTEM.Models.Consultation", b =>
                {
                    b.HasOne("WEB_BASED_PATIENT_MANAGEMENT_SYSTEM.Models.Appointment", "Appointment")
                        .WithMany()
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WEB_BASED_PATIENT_MANAGEMENT_SYSTEM.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .IsRequired();

                    b.HasOne("WEB_BASED_PATIENT_MANAGEMENT_SYSTEM.Models.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Appointment");

                    b.Navigation("Patient");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("WEB_BASED_PATIENT_MANAGEMENT_SYSTEM.Models.FamilyPlanningRecord", b =>
                {
                    b.HasOne("WEB_BASED_PATIENT_MANAGEMENT_SYSTEM.Models.Patient", "Patient")
                        .WithMany("FamilyPlanningRecords")
                        .HasForeignKey("PatientId");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("WEB_BASED_PATIENT_MANAGEMENT_SYSTEM.Models.NewbornRecord", b =>
                {
                    b.HasOne("WEB_BASED_PATIENT_MANAGEMENT_SYSTEM.Models.Patient", "Patient")
                        .WithMany("NewbornRecords")
                        .HasForeignKey("PatientId");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("WEB_BASED_PATIENT_MANAGEMENT_SYSTEM.Models.NotificationRead", b =>
                {
                    b.HasOne("WEB_BASED_PATIENT_MANAGEMENT_SYSTEM.Models.Appointment", null)
                        .WithMany()
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WEB_BASED_PATIENT_MANAGEMENT_SYSTEM.Models.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WEB_BASED_PATIENT_MANAGEMENT_SYSTEM.Models.Payment", b =>
                {
                    b.HasOne("WEB_BASED_PATIENT_MANAGEMENT_SYSTEM.Models.Consultation", "Consultation")
                        .WithOne()
                        .HasForeignKey("WEB_BASED_PATIENT_MANAGEMENT_SYSTEM.Models.Payment", "ConsultationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consultation");
                });

            modelBuilder.Entity("WEB_BASED_PATIENT_MANAGEMENT_SYSTEM.Models.PrenatalRecord", b =>
                {
                    b.HasOne("WEB_BASED_PATIENT_MANAGEMENT_SYSTEM.Models.Patient", "Patient")
                        .WithMany("PrenatalRecords")
                        .HasForeignKey("PatientId");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("WEB_BASED_PATIENT_MANAGEMENT_SYSTEM.Models.Service", b =>
                {
                    b.HasOne("WEB_BASED_PATIENT_MANAGEMENT_SYSTEM.Models.Appointment", "Appointment")
                        .WithMany()
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WEB_BASED_PATIENT_MANAGEMENT_SYSTEM.Models.Patient", "Patient")
                        .WithMany("Services")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Appointment");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("WEB_BASED_PATIENT_MANAGEMENT_SYSTEM.Models.Patient", b =>
                {
                    b.Navigation("FamilyPlanningRecords");

                    b.Navigation("NewbornRecords");

                    b.Navigation("PrenatalRecords");

                    b.Navigation("Services");
                });
#pragma warning restore 612, 618
        }
    }
}
